version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "springcloud-aws-s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-67ctdgxxxwve"
s3_prefix = "springcloud-aws-s3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
